"""Shared types and the LLMProvider protocol for all provider implementations.

This module defines the "contract" every provider must fulfill. Think of it as
an interface specification: any class that implements the :class:`LLMProvider`
protocol can be swapped in without changing the rest of the code.

Key concepts explained
----------------------
- **Protocol**: Python's structural typing equivalent of an interface. A class
  satisfies :class:`LLMProvider` if it has a ``chat()`` method with the right
  signature — no inheritance required. This is called "duck typing" at the
  type level.
- **Tool call**: When an LLM wants to run a tool (e.g. read a file), it doesn't
  run it directly — it returns a structured "I want to call tool X with these
  arguments" in its response. The framework then runs the tool and feeds the
  result back. :class:`ToolCall` captures that structured request.
- **Finish reason**: The LLM tells us *why* it stopped generating. ``"stop"``
  means a normal end of response; ``"tool_calls"`` means it paused to invoke
  tools and expects us to supply results before it continues.
- **Streaming**: When ``on_token`` is passed to ``chat()``, the provider yields
  each text token to the callback as it arrives from the API rather than waiting
  for the full response. ``LLMResponse.was_streamed`` tells the caller whether
  the text was already printed this way.

Talks to
--------
- All provider implementations (``openai_compatible.py``, ``anthropic.py``,
  ``lmstudio.py``) import these types.
- ``runner.py`` uses :class:`LLMResponse` to decide what to do next.
- ``__init__.py`` re-exports these types for external callers.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Protocol


@dataclass
class TokenUsage:
    """Token consumption for a single provider.chat() call.

    Attributes:
        input_tokens:  Tokens in the prompt sent to the model.
        output_tokens: Tokens the model generated in its response.
    """
    input_tokens: int
    output_tokens: int


@dataclass
class ToolCall:
    """Represents a single tool invocation requested by the LLM.

    When the model wants to call a tool, the API returns one or more of these.
    The runner executes each tool and sends back the results.

    Attributes:
        id (str): A unique identifier generated by the LLM for this specific
            tool call. Used to pair the result with the request.
        name (str): The name of the tool the model wants to invoke,
            e.g. ``"read"`` or ``"bash"``.
        arguments (dict): The parsed keyword arguments for the tool.
            Already converted from JSON string to a Python dict.
        error (str | None): Set by the provider when the model's argument JSON
            cannot be parsed. The runner feeds this back to the model as a
            tool-result observation so the model can retry with valid JSON.
            ``None`` for well-formed tool calls.
    """
    id: str
    name: str
    arguments: dict
    error: str | None = None


@dataclass
class LLMResponse:
    """The normalized response returned by any :class:`LLMProvider`.

    All providers convert their raw API responses into this common format so
    that :func:`run_turn` can work with any provider interchangeably.

    Attributes:
        text (str): The text content of the model's response. May be an empty
            string if the model only issued tool calls and produced no prose.
        tool_calls (list[ToolCall]): Zero or more tool invocation requests.
            If non-empty, ``finish_reason`` should be ``"tool_calls"``.
        finish_reason (str): Why the model stopped generating.
            - ``"stop"``       — normal end of response; this is the final answer.
            - ``"tool_calls"`` — model wants to call tools; loop continues.
        was_streamed (bool): ``True`` if ``text`` was already sent to the
            caller token-by-token via the ``on_token`` callback during the
            ``chat()`` call. When ``True``, the runner must *not* print
            ``text`` again — it has already appeared in the terminal.
            ``False`` for non-streaming calls or when the model produced no text.
    """
    text: str
    # field(default_factory=list) means each LLMResponse gets its own fresh list,
    # not a shared mutable default (a common Python pitfall with mutable defaults).
    tool_calls: list[ToolCall] = field(default_factory=list)
    finish_reason: str = "stop"
    # Streaming flag: set by the provider when on_token was called at least once.
    was_streamed: bool = False
    # None means the provider didn't return usage data (e.g. streaming on OpenAI-compatible).
    usage: "TokenUsage | None" = None


class LLMProvider(Protocol):
    """Structural protocol all LLM provider classes must satisfy.

    Any class with a ``chat()`` method matching this signature can be used
    wherever an :class:`LLMProvider` is expected — no explicit inheritance needed.

    This means swapping from OpenAI to Anthropic requires only changing which
    provider is created, not any of the code that uses the provider.
    """

    def chat(
        self,
        system: str,
        messages: list[dict],
        tools: list[dict],
        max_tokens: int,
        on_token: Callable[[str], None] | None = None,
    ) -> LLMResponse:
        """Send a conversation to the LLM and return its response.

        Args:
            system (str): The system prompt — instructions that define the
                agent's role and behavior. Sent before user messages.
            messages (list[dict]): The full conversation history. Each dict
                has ``"role"`` and ``"content"`` keys (plus optional
                ``"tool_calls"`` / ``"tool_call_id"`` for tool interactions).
            tools (list[dict]): Tool definitions in OpenAI format — the list
                of functions the model may call. Pass an empty list to disable
                tool use entirely.
            max_tokens (int): Maximum number of tokens the model may generate.
            on_token (Callable[[str], None] | None): Optional streaming callback.
                When provided, the provider uses the streaming API and calls
                this function with each text token as it arrives. The full
                text is still returned in :attr:`LLMResponse.text`.
                When ``None``, a single blocking request is made instead.

        Returns:
            LLMResponse: Normalized response with text, optional tool calls,
                the reason the model stopped generating, and a ``was_streamed``
                flag indicating whether tokens were already delivered via
                ``on_token``.
        """
        ...
